### ISSUE TITLE
Orderer v3: BFT Block Replication and Block Signature Verification

### ISSUE THREAD

**Issue by Param-S** [hyperledger/fabric#3411]
Refer [#48](https://github.com/hyperledger/fabric-rfcs/pull/48) for complete details

Workitems:

- [x] Story: Define and implement a generic BFT Block Replication Module
    - [x] [Implement a new interface BlockFetcher with source suspicious logic and reshuffling](https://github.com/hyperledger/fabric/issues/3412)
    - [x] [Implement a block attestation service](https://github.com/hyperledger/fabric/issues/3413)
    - [x] [Implement a block signature verification](https://github.com/hyperledger/fabric/issues/3414)

- [x] Story: Update peer module to use new block replication module
    - [x] [Update peer block deliver client to use new common block replication module](https://github.com/hyperledger/fabric/issues/3415)

- [x] Story: Update orderer module to use new block replication module
    - [x] [Update orderer block replicator client to use new common block replication module](https://github.com/hyperledger/fabric/issues/3416)

- [x] Story: Write Unit & Integration Tests
    - [x] [Add new Integration tests](https://github.com/hyperledger/fabric/issues/3417)

**Comment by tock-ibm** [comment]
The remaining tasks in this epic are now tracked by #4240
